### ISSUE TITLE
Unit tests failing with 401s using a new API key

### ISSUE THREAD

**Issue by michaellavelle** [IndicoDataSolutions/IndicoIo-Java#18]
Hi there

I just discovered Indico and it looks like a very interesting product! - I'm very keen to try out your APIs.

I checked out the IndicoIo-Java project and when running a number of the unit tests (eg IndicoBatchImageApiTest ),  I get one pass ( imageFeaturesResponseTest), but the other tests are failing with 401s.   I'm using the API key from my account dashboard with the tests - would this be expected to have the permissions to run these examples, or are there parts of the API not publicly available yet?

Many thanks,

Michael

**Comment by madisonmay** [comment]
Hi Michael,

Would you mind running the tests again?  It appears we had an issue with newly created keys being synced to our databases -- it should be resolved as of ~5 minutes ago.  Let me know if you have any further issues!

**Comment by madisonmay** [comment]
Confirmed resolved.... closing.
